ALTER TABLE `file`
    MODIFY COLUMN `MA_LK` VARCHAR(255) NULL;

UPDATE `file`
SET `MA_LK` = JSON_UNQUOTE(
    JSON_EXTRACT(
        `decode`,
        '$.DANHSACHHOSO.HOSO[0].FILEHOSO[0].NOIDUNGFILE.TONG_HOP.MA_LK'
    )
)
WHERE `MA_LK` IS NULL;

ALTER TABLE `file`
    MODIFY COLUMN `MA_LK` VARCHAR(255) NOT NULL,
    ADD UNIQUE KEY `uq_file_ma_lk` (`MA_LK`);
