CREATE TABLE IF NOT EXISTS `dan_toc` (
    `ma` CHAR(2) NOT NULL,
    `ten` VARCHAR(100) NOT NULL,
    `ten_goi_khac` TEXT DEFAULT NULL,
    `is_active` TINYINT(1) NOT NULL DEFAULT 1,
    `source_url` VARCHAR(500) NOT NULL,
    PRIMARY KEY (`ma`),
    KEY `idx_dan_toc_ten` (`ten`),
    KEY `idx_dan_toc_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `dan_toc` (`ma`, `ten`, `ten_goi_khac`, `is_active`, `source_url`) VALUES
('01', 'Kinh', 'Việt', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('02', 'Tày', 'Thổ, Ngạn, Phén, Thù Lao, Pa Dí, Tày Khao', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('03', 'Thái', 'Tày Đăm, Tày Mười, Tày Thanh, Mán Thanh, Hàng Bông, Tày Mường, Pa Thay, Thổ Đà Bắc', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('04', 'Hoa', 'Hán, Triều Châu, Phúc Kiến, Quảng Đông, Hải Nam, Hạ, Xạ Phạng', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('05', 'Khơ-me', 'Cur, Cul, Cu, Thổ, Việt gốc Miên, Krôm', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('06', 'Mường', 'Mol, Mual, Mọi, Mọi Bi, Ao Tá, Ậu Tá', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('07', 'Nùng', 'Xuồng, Giang, Nùng An, Phàn Sinh, Nùng Cháo, Nùng Lòi, Quý Rim, Khèn Lài', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('08', 'HMông', 'Mèo, Hoa, Mèo Xanh, Mèo Đỏ, Mèo Đen, Ná Mẻo, Mán Trắng', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('09', 'Dao', 'Mán, Động, Trại, Xá, Dìu, Miên, Kiềm, Miền, Quần Trắng, Dao Đỏ, Quần Chẹt, Lô Giang, Dao Tiền, Thanh Y, Lan Tẻn, Đại Bản, Tiểu Bản, Cóc Ngáng, Cóc Mùn, Sơn Đầu', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('10', 'Gia-rai', 'Giơ-rai, Tơ-buăn, Chơ-rai, Hơ-bau, Hđrung, Chor', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('11', 'Ngái', 'Xín, Lê, Đản, Khách Gia', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('12', 'Ê-đê', 'Ra-đê, Đê, Kpạ, A-đham, Krung, Ktul, Đliê Ruê, Blô, Epan, Mđhur, Bih', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('13', 'Ba na', 'Giơ-lar. Tơ-lô, Giơ-lâng, Y-lăng, Rơ-ngao, Krem, Roh, ConKđe, A-la Công, Kpăng Công, Bơ-nâm', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('14', 'Xơ-Đăng', 'Xơ-teng, Hđang, Tơ-đra, Mơ-nâm, Ha-lăng, Ca-dong, Kmrâng, ConLan, Bri-la, Tang', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('15', 'Sán Chay', 'Cao Lan, Sán Chỉ, Mán Cao Lan, Hờn Bạn, Sơn Tử', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('16', 'Cơ-ho', 'Xrê, Nốp, Tu-lốp, Cơ-don, Chil, Lat, Lach, Trinh', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('17', 'Chăm', 'Chàm, Chiêm Thành, Hroi', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('18', 'Sán Dìu', 'Sán Dẻo, Trại, Trại Đất, Mán, Quần Cộc', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('19', 'Hrê', 'Chăm Rê, Chom, Krẹ Luỹ', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('20', 'Mnông', 'Pnông, Nông, Pré, Bu-đâng, ĐiPri, Biat, Gar, Rơ-lam, Chil', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('21', 'Ra-glai', 'Ra-clây, Rai, Noang, La-oang', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('22', 'Xtiêng', 'Xa-điêng', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('23', 'Bru-Vân Kiều', 'Bru, Vân Kiều, Măng Coong, Tri Khùa', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('24', 'Thổ', 'Kẹo, Mọn, Cuối, Họ, Đan Lai, Ly Hà, Tày Pọng, Con Kha, Xá Lá Vàng', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('25', 'Giáy', 'Nhắng, Dẩng, Pầu Thìn Nu Nà, Cùi Chu, Xa', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('26', 'Cơ-tu', 'Ca-tu, Cao, Hạ, Phương, Ca-tang', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('27', 'Gié Triêng', 'Đgiéh, Tareb, Giang Rẫy Pin, Triêng, Treng, Ta-riêng, Ve, Veh, La-ve, Ca-tang', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('28', 'Mạ', 'Châu Mạ, Mạ Ngăn, Mạ Xóp, Mạ Tô, Mạ Krung', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('29', 'Khơ-mú', 'Xá Cẩu, Mứn Xen, Pu Thênh, Tềnh, Tày Hay', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('30', 'Co', 'Cor, Col, Cùa, Trầu', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('31', 'Tà-ôi', 'Tôi-ôi, Pa-co, Pa-hi, Ba-hi', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('32', 'Chơ-ro', 'Dơ-ro, Châu-ro', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('33', 'Kháng', 'Xá Khao, Xá Súa, Xá Dón, Xá Dẩng, Xá Hốc, Xá Ái, Xá Bung, Quảng Lâm', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('34', 'Xinh-mun', 'Puộc, Pụa', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('35', 'Hà Nhì', 'U Ni, Xá U Ni', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('36', 'Chu ru', 'Chơ-ru, Chu', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('37', 'Lào', 'Là Bốc, Lào Nọi', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('38', 'La Chí', 'Cù Tê, La Quả', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('39', 'La Ha', 'Xá Khao, Khlá Phlạo', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('40', 'Phù Lá', 'Bồ Khô Pạ, Mu Di Pạ Xá, Phó, Phổ, Va Xơ', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('41', 'La Hủ', 'Lao, Pu Đang, Khù Xung, Cò Xung, Khả Quy', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('42', 'Lự', 'Lừ, Nhuồn, Duôn', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('43', 'Lô Lô', 'Mun Di', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('44', 'Chứt', 'Sách, Máy, Rục, Mã-liêng, A-rem, Tu vang, Pa-leng, Xơ-Lang, Tơ-hung, Chà-củi, Tắc-củi, U-mo, Xá Lá Vàng', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('45', 'Mảng', 'Mảng Ư, Xá Lá Vàng', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('46', 'Pà Thẻn', 'Pà Hưng, Tống', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('47', 'Co Lao', NULL, 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('48', 'Cống', 'Xắm Khống, Mấng Nhé, Xá Xeng', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('49', 'Bố Y', 'Chủng Chá, Trọng Gia, Tu Di, Tu Din', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('50', 'Si La', 'Cù Dề Xừ, Khả pẻ', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('51', 'Pu Péo', 'Ka Pèo, Pen Ti Lô Lô', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('52', 'Brâu', 'Brao', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('53', 'Ơ Đu', 'Tày Hạt', 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('54', 'Rơ măm', NULL, 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('55', 'Người nước ngoài', NULL, 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/'),
('56', 'Không rõ', NULL, 1, 'https://www.nso.gov.vn/phuong-phap-luan-thong-ke/danh-muc/cac-dan-toc-viet-nam/')
ON DUPLICATE KEY UPDATE
    `ten` = VALUES(`ten`),
    `ten_goi_khac` = VALUES(`ten_goi_khac`),
    `is_active` = VALUES(`is_active`),
    `source_url` = VALUES(`source_url`);
