CREATE TABLE IF NOT EXISTS `quanhuyen_phuongxa` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `ma_tinh_cu` INT NOT NULL,
    `ten_tinh_cu` VARCHAR(150) NOT NULL,
    `ma_quanhuyen_cu` INT NOT NULL,
    `ten_quanhuyen_cu` VARCHAR(150) NOT NULL,
    `loai_quanhuyen_cu` VARCHAR(30) NOT NULL,
    `ma_phuongxa_cu` INT NOT NULL,
    `ten_phuongxa_cu` VARCHAR(150) NOT NULL,
    `loai_phuongxa_cu` VARCHAR(30) NOT NULL,
    `ma_tinh_moi` INT NOT NULL,
    `ten_tinh_moi` VARCHAR(150) NOT NULL,
    `ma_phuongxa_moi` INT NOT NULL,
    `ten_phuongxa_moi` VARCHAR(150) NOT NULL,
    `loai_phuongxa_moi` VARCHAR(30) NOT NULL,
    `sap_nhap_mot_phan` TINYINT(1) NOT NULL DEFAULT 0,
    `ngay_hieu_luc` DATE NOT NULL DEFAULT '2025-07-01',
    `nguon` VARCHAR(500) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_qhpx_cu_moi` (`ma_phuongxa_cu`, `ma_phuongxa_moi`),
    KEY `idx_qhpx_quanhuyen_cu` (`ma_quanhuyen_cu`),
    KEY `idx_qhpx_phuongxa_cu` (`ma_phuongxa_cu`),
    KEY `idx_qhpx_phuongxa_moi` (`ma_phuongxa_moi`),
    KEY `idx_qhpx_tinh_cu_moi` (`ma_tinh_cu`, `ma_tinh_moi`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
