CREATE TABLE IF NOT EXISTS `danhmuc_thuoc` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `stt_nguon` INT UNSIGNED DEFAULT NULL,
    `ma_hoat_chat` VARCHAR(50) DEFAULT NULL,
    `ten_hoat_chat` TEXT NOT NULL,
    `duong_dung_dang_bao_che` TEXT DEFAULT NULL,
    `nong_do_ham_luong` VARCHAR(255) DEFAULT NULL,
    `ten_thuoc` TEXT NOT NULL,
    `sdk_gpnk` VARCHAR(255) DEFAULT NULL,
    `sdk_chuan_hoa` VARCHAR(255) DEFAULT NULL,
    `nha_san_xuat` TEXT DEFAULT NULL,
    `nuoc_san_xuat` VARCHAR(255) DEFAULT NULL,
    `quy_cach_dong_goi` TEXT DEFAULT NULL,
    `don_vi_tinh` VARCHAR(100) DEFAULT NULL,
    `so_luong` DECIMAL(20,3) DEFAULT NULL,
    `don_gia` DECIMAL(20,3) DEFAULT NULL,
    `thanh_tien` DECIMAL(20,3) DEFAULT NULL,
    `nha_thau_trung_thau` TEXT DEFAULT NULL,
    `nhom_tieu_chi` VARCHAR(50) DEFAULT NULL,
    `goi_thau` VARCHAR(50) DEFAULT NULL,
    `don_vi_cong_bo` TEXT DEFAULT NULL,
    `tinh_thanh` VARCHAR(255) DEFAULT NULL,
    `so_quyet_dinh` VARCHAR(255) DEFAULT NULL,
    `ngay_cong_bo` DATE DEFAULT NULL,
    `source_url` VARCHAR(1000) DEFAULT NULL,
    `source_page` SMALLINT UNSIGNED DEFAULT NULL,
    `is_active` TINYINT(1) NOT NULL DEFAULT 1,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_danhmuc_thuoc_ma_hoat_chat` (`ma_hoat_chat`),
    KEY `idx_danhmuc_thuoc_sdk_chuan_hoa` (`sdk_chuan_hoa`),
    KEY `idx_danhmuc_thuoc_ten_thuoc` (`ten_thuoc`(100)),
    KEY `idx_danhmuc_thuoc_tinh_thanh` (`tinh_thanh`),
    KEY `idx_danhmuc_thuoc_ngay_cong_bo` (`ngay_cong_bo`),
    KEY `idx_danhmuc_thuoc_source_page` (`source_page`),
    KEY `idx_danhmuc_thuoc_is_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
